backend:
    name: github
    repo: kallie-rollenhagen/kallierollenhagen-com
    branch: main
    base_url: https://jqj.rlj.mybluehost.me/website_e1e2df13/oauth/public
    auth_endpoint: /auth

media_folder: "src/assets/images/"
public_folder: "/assets/images/"

collections:
  - name: art
    label: Art Page
    files:
      - label: Art
        name: art
        file: "src/content/art.njk"
        fields:
          - { label: Title, name: title, widget: string }
  - name: test
    label: Test Page
    files:
      - label: Test2
        name: test
        file: src/content/test2.md
        fields:
          - { label: Title, name: title, widget: string }