backend:
    name: github
    repo: kallie-rollenhagen/kallierollenhagen-com
    branch: main
    base_url: https://decap-proxy.hallenj.workers.dev
    auth_endpoint: /auth

media_folder: "src/assets/images/"
public_folder: "/assets/images"
site_url: "https://kallierollenhagen.com"

gallery_field: &gallery_field
  label: Gallery
  name: gallery
  widget: object
  fields:
    - label: Gallery Type
      name: type
      widget: select
      options:
        - grid
        - masonry

    - label: Lightbox
      name: lightbox
      widget: boolean
      default: false

    - label: Rows
      name: rows
      widget: list
      fields:
        - label: Layout
          name: layout
          widget: select
          required: false
          options:
            - halves
            - thirds
            - left-wide
            - right-wide
            - full-width

        - label: Image Fit
          name: object_fit
          widget: select
          default: contain
          options:
            - { label: Contain, value: contain }
            - { label: Cover, value: cover }

        - label: Elements
          name: elements
          widget: list
          types:

            - label: Image
              name: image
              widget: object
              fields:
                - { label: File, name: file, widget: image }
                - { label: Alt Text, name: alt, widget: string, required: false }
                - { label: Caption, name: caption, widget: string, required: false }

            - label: Text
              name: text
              widget: object
              fields:
                - { label: Text Content, name: text, widget: 'richtext' }
            
            - label: Spacer
              name: spacer
              widget: object
              fields:
                - label: Spacer
                  name: spacer
                  widget: hidden
                  default: true

collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: src/content/index.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: seoDescription, widget: string }
          - label: Slides
            name: slides
            widget: list
            fields:
              - { label: Image, name: file, widget: image }
              - { label: Alt Text, name: alt, widget: string }
      - label: Design Page
        name: design
        file: src/content/design.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: Design Projects
            name: design_projects
            widget: list
            field:
              label: Project
              name: project
              widget: relation
              collection: projects
              search_fields: ["title"]
              value_field: "{{slug}}"
              display_fields: ["title"]
      - label: MCAD Page
        name: mcad
        file: src/content/mcad.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: Design Projects
            name: design_projects
            widget: list
            field:
              label: Project
              name: project
              widget: relation
              collection: projects
              search_fields: ["title"]
              value_field: "{{slug}}"
              display_fields: ["title"]
      - label: Sketchbook Page
        name: sketchbook
        file: src/content/sketchbook.md
        fields:
          - { label: Title, name: title, widget: string }
          - *gallery_field
      - label: Photography Page
        name: photography
        file: src/content/photography.md
        fields:
          - { label: Title, name: title, widget: string }
          - *gallery_field
      - label: About Page
        name: about
        file: src/content/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Photo"
            name: "photo"
            widget: "object"
            fields:
              - {label: "File", name: "file", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string"}
              - {label: "Credit", name: "credit", widget: "string"}
          - label: "Contact Info"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Location", name: "location", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - {label: "Bio", name: "bio", widget: "richtext"}
          - label: "Ideal Clients"
            name: "clients"
            widget: "list"
            fields:
              - label: Client
                name: client
                widget: string
          - label: "Education"
            name: "education"
            widget: list
            fields:
              - {label: "School", name: "school", widget: "string"}
              - {label: "Degree", name: "degree", widget: "string"}

  - name: "projects"
    label: "Design Projects"
    folder: "src/content/design/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: Publish
        name: publish
        widget: boolean
        default: false
      - { label: "Roles Played by Kallie", name: "roles_played", widget: "string" }
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields:
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Person", name: "person", widget: "string"}
      - {label: "Project Description", name: "project_description", widget: "richtext"}
      - label: "Main Image"
        name: "main_image"
        widget: "object"
        fields:
          - {label: "File", name: "file", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
      - label: "Thumbnail Image"
        name: "thumbnail_image"
        widget: "object"
        fields:
          - {label: "File", name: "file", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
      - *gallery_field

  - name: admin
    label: Site Administration
    files:

      - label: README.md
        name: readme
        file: README.md
        delete: false
        fields:
          - label: Content
            name: body
            widget: markdown

      - label: styles.css
        name: site_css
        file: src/assets/css/styles.css
        delete: false
        frontmatter_delimiter: ["{", "}"]
        fields:
          - label: CSS
            name: body
            widget: code
            default_language: css
            allow_language_selection: false
            output_code_only: true