backend:
    name: github
    repo: kallie-rollenhagen/kallierollenhagen-com
    branch: main
    base_url: https://decap-proxy.hallenj.workers.dev
    auth_endpoint: /auth

media_folder: "src/assets/images/"
public_folder: "/assets/images/"

collections:

  - name: "projects"
    label: "Design Projects"
    folder: "src/content/design/"
    create: true
    format: frontmatter
    extensions: njk
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      
  - name: art
    label: Art
    format: frontmatter
    files:
      - label: Art
        name: art
        file: "src/content/art.njk"
        fields:
          - { label: Title, name: title, widget: string }
          - {label: "Body", name: "body", widget: "markdown"}

  - name: photography
    label: Photography
    files:
      - label: Test2
        name: test
        file: src/content/test2.md
        fields:
          - { label: Title, name: title, widget: string }
          - {label: "Body", name: "body", widget: "markdown"}